[package]
name = "HTTP-Server"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
serde = "1.0.217"
serde_json = "1.0.138"
serde_urlencoded = "0.7.1"
tokio = { version = "1", features = ["full"] }

